version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./ip-address.txt:/ip-address.txt
    environment:
      - NGINX_SERVER_NAME=$(cat /ip-adress.txt)
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - spring-petclinic_default
networks:
  spring-petclinic_default:
    name: spring-petclinic_default  
