version: '3.8'
services:
  petclinic:
    build: .
    container_name: petclinic-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - spring-petclinic_default
    environment:
      - SPRING_PROFILES_ACTIVE=mysql

  mysqlserver:
    container_name: mysql-docker
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - spring-petclinic_default
networks:
  spring-petclinic_default:
    external: true
