version: '3'
services:
  petclinic:
    build: .
    container_name: petclinic-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
    networks:
      - mysqlnet

  mysqlserver:
    container_name: mysql-docker
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - mysqlnet

networks:
  mysqlnet:
    name: mysqlnet
